name: focus_currency
description: "The Ultimate Focus Tool."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # SYSTEM CONTROL
  device_apps: ^2.2.0
  usage_stats: ^1.2.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.2
  
  # UI
  google_fonts: ^6.1.0
  animate_do: ^3.1.0
  glassmorphism: ^3.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true